# docker-compose.yml
services:
  blog:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    command: ["bundle", "exec", "jekyll", "serve", "--watch", "--host", "0.0.0.0"] 

